name: ugodev-test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: 
      - main
      - development

jobs:
  build-old:
    name: Go 1.15
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.15'

    - name: Check out
      uses: actions/checkout@v3

    - name: Install Staticcheck
      run: |
        GOBIN=${GOBIN:-"$HOME/go/bin"}
        mkdir -p "$GOBIN"
        echo "$GOBIN" >> "$GITHUB_PATH"
        export GO111MODULE=on
        cd "$GOBIN" && go get honnef.co/go/tools/cmd/staticcheck@2021.1
    
    - name: Lint Go
      run: staticcheck ./...
    
    - name: Test patcher
      working-directory: ./patcher
      run: go test -race -cover ./...

    - name: Build Playground
      working-directory: ./playground
      run: |
        npm install --global yarn
        yarn install
        yarn run lint
        yarn run build
      env:
        CI: true
    
    - name: Test Playground
      working-directory: ./playground
      run: |
        make test
        yarn run test
      env:
        CI: true

  build-new:
    name: Go 1.17
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Check out
      uses: actions/checkout@v3
    
    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2022.1
    
    - name: Lint Go
      run: staticcheck ./...
    
    - name: Test patcher
      working-directory: ./patcher
      run: go test -race -cover ./...
    
    - name: Build Playground
      working-directory: ./playground
      run: |
        npm install --global yarn
        yarn install
        yarn run lint
        yarn run build
      env:
        CI: true
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: playground
        path: ./playground/dist
        if-no-files-found: error
    
    - name: Test Playground
      working-directory: ./playground
      run: |
        make test
        yarn run test
      env:
        CI: true
