name: ugodev-test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: govulncheck
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    
    - name: Run govulncheck
      run: govulncheck ./...

  build:
    needs: govulncheck
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Check out
      uses: actions/checkout@v4
    
    - name: Test patcher
      run: go test -race -cover ./...
      working-directory: ./patcher
    
    - name: Build Playground
      run: |
        set -ex
        npm install --global yarn
        yarn install
        make production
        yarn run lint
        yarn run build
      working-directory: ./playground
      env:
        CI: true
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: playground
        path: ./playground/dist
        if-no-files-found: error
    
    - name: Test Playground
      run: make test
      working-directory: ./playground
      env:
        CI: true
